CREATE TABLE `USERS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `EMAIL` VARCHAR(100) DEFAULT NULL,
  `PHONENO` VARCHAR(100) DEFAULT NULL,
  `PASSWORD` VARCHAR(100) DEFAULT NULL,
  `USERTYPE` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=LATIN1;

CREATE TABLE `BLOGPOST` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(100) DEFAULT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `BLOGCONTENT` TEXT DEFAULT NULL,
  `DATE` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=LATIN1;

INSERT INTO USERS VALUES(
  '',
  'Kenedy Cheruiyot',
  'cheruiyotkenedy@gmail.com',
  '213213',
  'ken',
  'Admin'
);

INSERT INTO USERS VALUES(
  '',
  'Labrador Gichohi',
  'labradorgichohi@gmail.com',
  '213213',
  'labu',
  'Admin'
);

INSERT INTO USERS VALUES(
  '',
  'Winfrida',
  'winfrida@sepke.org',
  '213213',
  'winfrida',
  'Admin'
);